### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ferdnyc** [gregkh/usbview#14]
Since the last official release (2.0) was [in 2012](https://github.com/gregkh/usbview/releases/tag/v2.0), none of the merged PRs are included, and some distros are still packaging that version, or a locally-modified one.

(Fedora, for instance, [adds](https://src.fedoraproject.org/rpms/usbview/blob/master/f/org.fedoraproject.usbview.policy) its own polkit file (#12) and reencodes the ChangeLog file to UTF-8, but otherwise [packages](https://src.fedoraproject.org/rpms/usbview/blob/master/f/usbview.spec) 2.0 unmodified from the 2012 release. That means that even the USB-3 bus speed labels (#8) aren't displayed in the Fedora `usbview`.)

Pushing out a 2.1 release would hopefully spur downstream packagers into updating.

**Comment by telans** [comment]
ditto

**Comment by gregkh** [comment]
Ok, I can cut a new release and then work on fixing this whole thing "for real" to not require access to debugfs...

**Comment by telans** [comment]
@gregkh pinging regarding making a release (unless there are things that need to be done first)

**Comment by telans** [comment]
Bump?

**Comment by ferdnyc** [comment]
Hrm. It seems even Fedora rawhide is still on `usbview-2.0-19.fc35`.

Looks like a maintainer needs poking. I'll grab my stick.

**Comment by ferdnyc** [comment]
Oh, hah! Spec file updates for 2.2 were checked in [two hours ago](https://src.fedoraproject.org/rpms/usbview/commits/rawhide). Well, that was easy!

**Comment by gregkh** [comment]
3.0 is now out as well, removing the need for root access entirely, please poke them to update to that.

**Comment by ferdnyc** [comment]
@gregkh Will do, no sense putting 2.2 through the update process just to supersede it.

**Comment by ferdnyc** [comment]
[Poked](https://src.fedoraproject.org/rpms/usbview/pull-request/1).
