### ISSUE TITLE
Feature Request: Show Vendor and Product

### ISSUE THREAD

**Issue by arrmo** [gregkh/usbview#15]
Hi,

This is not a bug, just a thought of an enhancement - so want to clearly call it that 😄. It would be nice to show the Vendor and Product name ... from usb.ids (lookup of sorts?).

Just a thought.

Thanks!

**Comment by gregkh** [comment]
usbutils should show you this information (by using `lsusb`) so I doubt adding this here would really help out much given that this program doesn't usually even work for people :)

**Comment by arrmo** [comment]
No worries, completely understand. Thanks!

**Comment by idallen** [comment]
I, too, wish that usbview would be a one-stop viewer that didn't make me have to use lsusb to look up the Vendor/Product info.
Computers are good at that sort of information combining, so that humans can do more worthwhile things.  :-)

**Comment by fake-rookie** [comment]
maybe just use `lsusb.py`, if want to see Vendor .
