### ISSUE TITLE
make error #2

### ISSUE THREAD

**Issue by zdens** [gregkh/usbview#20]
Hi!

while trying to build on my laptop MSI GS63 Stealth under Kubuntu 21.10 I'm getting build error after calling command `make`:
```
make  all-am
make[1]: Entering directory '/mnt/data/repos/github/usbview'
  CC       main.o
mkdir -p $(dirname hicolor/64x64/apps/usbview_icon.xpm)
convert -geometry $(basename $(dirname $(dirname hicolor/64x64/apps/usbview_icon.xpm))) usbview_icon.svg hicolor/64x64/apps/usbview_icon.xpm
convert: no images defined `hicolor/64x64/apps/usbview_icon.xpm' @ error/convert.c/ConvertImageCommand/3322.
make[1]: *** [Makefile:992: hicolor/64x64/apps/usbview_icon.xpm] Error 1
make[1]: Leaving directory '/mnt/data/repos/github/usbview'
make: *** [Makefile:359: all] Error 2
```

What am I doing wrong?

after configuration I saw this summary:

        usbview 2.1
        ===========

        prefix:                 /usr/local
        datarootdir:            ${prefix}/share
        datadir:                ${datarootdir}
        mandir:                 ${datarootdir}/man

        compiler:               gcc
        cflags:                 -g -O2
        ldflags:

**Comment by fake-rookie** [comment]
did you install GTK lib?
need GTK to compile this.

**Comment by zdens** [comment]
yes, I did:
![image](https://user-images.githubusercontent.com/35842917/146633551-5cb3476d-7b33-45ac-acd5-2f3e63523c68.png)

**Comment by fake-rookie** [comment]
can you post the whole information of run `./autogen.sh` ?

**Comment by zdens** [comment]
commands output is attached
[log.txt](https://github.com/gregkh/usbview/files/7770239/log.txt)

**Comment by fake-rookie** [comment]
it looks like need `convert` program. 
that convert `.svg` format to `.png` format.
but ,  i don't know what that is.

**Comment by telans** [comment]
`imagemagick` installs the convert tool

**Comment by zdens** [comment]
I do have imagemagick with convert tool installed:
![image](https://user-images.githubusercontent.com/35842917/147451107-5ecd8fbe-a55f-4997-80f2-1aaf2579c847.png)

**Comment by fake-rookie** [comment]
did you install with `sudo make install` ?

**Comment by zdens** [comment]
> did you install with `sudo make install` ?

what package are you asking about?

imagemagick was installed earlier (I don't remember the date) but this was done via apt-get so, yes, with `sudo`

if the question is about usbview then no, I did not due to `make` has been failed

**Comment by fake-rookie** [comment]
i'm talking the the *Makefile* of `usbview`.

type `sudo make install` after `make`

**Comment by zdens** [comment]
the same error:
![image](https://user-images.githubusercontent.com/35842917/147572460-3ab440fa-8442-42f9-bb18-85bbb69c12f2.png)

**Comment by fake-rookie** [comment]
in the `usbview` directory, type:
```
ls hicolor/* && ls hicolor/64x64/apps/*
```

if no any files in the directory, i think is `convert` command error in `Makefile`.

**Comment by gregkh** [comment]
`convert` is the tool that does the image conversion here.  

What version of the tool do you have?  You can find this by the output of `convert --version`

Here is the output on my development machine:
```$ convert --version
Version: ImageMagick 7.1.0-19 Q16-HDRI x86_64 2021-12-22 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (11.1)
```

**Comment by zdens** [comment]
here is my convert tool:
![image](https://user-images.githubusercontent.com/35842917/150191265-3217961c-9ed5-41fa-ab6a-bae48679cc2e.png)

**Comment by gregkh** [comment]
Try not building as root.

If you check out the repo, do the following commands:
```git clean -fdx
./autogen
make```
what is the full output of that?

**Comment by gregkh** [comment]
Also make sure you have the `coreutils` package installed, perhaps you need that for `basename` and `dirname`?

**Comment by gregkh** [comment]
and finally, what is your full path?  To find that out, provide the output of `pwd` at the command line.

**Comment by ferdnyc** [comment]
Doesn't ImageMagick's SVG rendering use Inkscape as a backend? That might need to be installed as well, in order to render SVG to XPM.

**Comment by ferdnyc** [comment]
(Significantly, I _don't_ see any hint of an SVG delegate on the `convert --version` output @zdens posted. Mine looks like this:
```sh
$ convert --version
Version: ImageMagick 6.9.12-32 Q16 x86_64 2021-12-04 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib
```
Note the `rsvg` in the delegate list. (So I guess I was wrong about Inkscape, or at least it's not the only option.)

**Comment by ferdnyc** [comment]
Basically, @zdens, I think you need to install "some way" for ImageMagick to process SVG files into pixel data, something it can't do natively without a helper. If you _don't_ have your distro's `librsvg2` package installed, just adding that might be enough all by itself. (You'll know if the `convert --version` output gains an `rsvg` delegate. But I'm not sure if that can happen dynamically or if it needs to be recompiled to add in librsvg2 support.)

You could also try installing Inkscape, since like I said I'm pretty sure ImageMagick is _capable_ of using it as an SVG delegate as well. And that route is less likely to require a recompile.

If just installing either/both of those doesn't work, you'll probably need to install the librsvg2 development headers as well, then rebuild ImageMagick to pick it up.

**Comment by fake-rookie** [comment]
Or use other tools can change `xpm` to `svg`. and rewrite the `Makefile`

**Comment by ferdnyc** [comment]
That's definitely also an option, though realistically there aren't a lot of alternatives when going to XPM (other direction, @fake-rookie) which is not a common output format for tools to support. `librsvg2` itself has an `rsvg-convert` utility (in the `librsvg2-bin` Debian package or `librsvg2-tools` RPM package)... but it can't write XPM. You'd have to convert to PNG, then find a PNG-to-XPM converter. Which would probably be ImageMagick. :rofl: 

ImageMagick's flexibility and extensible format support has made it the de facto standard converter for good reason.

**Comment by zdens** [comment]
oh, @ferdnyc, in my distro I've got `librsvg2-bin` but its installation didn't solve the problem.

but installation of `inkscape` did solve conversion problem, unfortunately I cannot derive which package from installed
```
fig2dev inkscape libimage-magick-perl libimage-magick-q16-perl libmagick++-6.q16-8 libpotrace0 libwmf-bin python3-numpy python3-scour
```
did the trick.

**Comment by gregkh** [comment]
Great, closing this now that you got it building properly.
