### ISSUE TITLE
feature request: keyboard shortcuts

### ISSUE THREAD

**Issue by barak** [gregkh/usbview#23]
I'm forwarding a reasonable wishlist that was filed against the debian usbview package, namely a request for a keyboard shortcut 'q' or 'C-q' or 'C-w' or ESC or something like that, to quit. And maybe 'C-l' or 'r' to refresh? (You can navigate to the QUIT button and click it with RET, so it is possible to quit using the keyboard, but inconvenient.)

**Comment by ferdnyc** [comment]
Not that I'm arguing **against** <kbd>Ctrl</kbd>+<kbd>Q</kbd> and/or <kbd>Ctrl</kbd>+<kbd>W</kbd> shortcuts, as I agree that seems perfectly reasonable, but just as another workaround: Under any window manager I'm familiar with over the past 15+ years, <kbd>Alt</kbd>+<kbd>F4</kbd> should be supported as a universal "close window" shortcut. (Which will also quit the application, if it's the last window open for it.)

So, that's another option that should be already ready already. One I suppose we can thank/blame Windows for.

**Comment by barak** [comment]
Huh! Did not know that; thanks.

**Comment by gregkh** [comment]
Yes, alt+f4 works fine for closing the window.

As this is not a "real" GNOME application, but rather a raw GTK+ one, there is no real specific guideline for what should the keyboard shortcuts be for closing the application and the like.  So I'll just leave it as-is for now, thanks!
