### ISSUE TITLE
nest interfaces and endpoints

### ISSUE THREAD

**Issue by albfan** [gregkh/usbview#24]
Is it possible to add nodes for interfaces and endpoints instead of just output that for each bus:device?

Maybe that's only for input devices, if not, that would be another pro of using a GUI

**Comment by gregkh** [comment]
I don't understand what you mean by nodes for interfaces and endpoints.  Can you provide an example?

**Comment by ferdnyc** [comment]
I think @albfan was suggesting something like this (correct me if I'm wrong!)

Right now `usbview` might show this tree:

```text
EHCI Host Controller
  hub
    USB 2.0 Hub
      USB Keyboard
```
with the details for the `USB Keyboard` device in the text widget to the right.

Instead, the suggestion was, have the tree show this:

```text
EHCI Host Controller
  hub
    USB 2.0 Hub
      USB Keyboard
        Interface 0
          Endpoint 81
        Interface 1
          Endpoint 82
```
...With the appropriate details migrated to each row in the tree.

Seems a little excessive to me, but anyway I believe that was the proposal.

**Comment by gregkh** [comment]
Ah, yeah, that makes sense.  And isn't something that I'm going to change anytime soon, devices are the limit at the moment for the left column, the other information is all at a device level.
