### ISSUE TITLE
Add brief description how to build it

### ISSUE THREAD

**Issue by axel-h** [gregkh/usbview#28]
There should be a brief description how to build it - even if this is considered trivial. Especially, is there a way to make an out-of-source build, so the no files are generated in the git source folder? Seems `autogen.sh` must be invoked from the source folder and will always generate files there?

**Comment by gregkh** [comment]
Yes, `autogen.sh` must be run, or you can run the autotool commands "by hand" if you want to, that's normal.

And the autotool requirements will drop files into the git tree, sorry, that's just how the build works.  Once you have a working build tree, or use a tarball, then you can create a tree that can be built from that is not in the root directory, but again, that's a feature of autotools, not anything specific here.

Also, the number of people building this on their own should be almost none, distros provide the package for you already, right?

**Comment by axel-h** [comment]
> distros provide the package for you already, right?

Usually, yes. Unfortunately, I'm on a RHEL8 environment, where there is nothing, and thus I ended up having to building it....

**Comment by gregkh** [comment]
If you are stuck with RHEL8, you have bigger issues than usbview :)

Good luck!
