### ISSUE TITLE
installer warnings

### ISSUE THREAD

**Issue by aardvarkkrill** [gregkh/usbview#7]
two parts to this minor issue: 

(1) INSTALL document says to run "configure", but doesn't say that you have to make the configure file (? by running autogen,sh) 
and 
(2) when I ran autogen.sh it ran correctly but threw up several warnings:
~/git/usbview$ . autogen.sh  
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:4: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:4: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:10: installing './compile'
configure.in:4: installing './install-sh'
configure.in:4: installing './missing'
Makefile.am:3: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
Makefile.am: installing './depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'

**Comment by Neo20067** [comment]
$git ~/inint--neo20067*/

**Comment by gregkh** [comment]
Should now all be resolved.
